# Makefile for engine

$CC=g++
$FLAGS=-std=c++11


EG_Scene.o: Scene.o
	$(CC) -c EG_Scene.cpp -o EG_Scene.o $(FLAGS)
	
Cell.o:
	$(CC) -c Cell.cpp -o Cell.o $(FLAGS)
	
	
Controller.o:
	$(CC) -c Controller.cpp -o Controller.o $(FLAGS)
	
Entity.o:
	$(CC) -c Entity.cpp -o Entity.o $(FLAGS)

EntityManager.o
	$(CC) -c EntityManager.cpp -o EntityManager.o $(FLAGS)
	
Lobby.o:
	$(CC) -c Lobby.cpp -o Lobby.o $(FLAGS)
	
Map.o
	$(CC) -c Map.cpp -o Map.o $(FLAGS)
	
Scene.o:
	$(CC) -c Scene.cpp -o Scene.o $(FLAGS)
	
TextureManager.o:
	$(CC) -c TextureManager.cpp -o TextureManager.o $(FLAGS)
	
TileManager.o
	$(CC) -c TileManager.cpp -o TileManager.o $(FLAGS)
	
World.o:
	$(CC) -c World.cpp -o World.o -o World.o $(FLAGS)