#ifndef _GAME_SETTINGS_H_
#define _GAME_SETTINGS_H_

#define MIN_REQUIRED_PLAYERS 1
#define NUM_VESSELS 1
#define SERVER_INITIAL_TIMER_VALUE 1
#define GAME_ROUND_LENGTH_SECONDS 100
#define MUSIC_OFF 0
#define MUSIC_ON 1
#define SCOREBOARD_LENGTH_SECONDS 1
#endif
