#ifndef _GAME_SETTINGS_H_
#define _GAME_SETTINGS_H_

#define DEBUG 0
#define ALLOW_SINGLE_PLAYER 0
#define MIN_REQUIRED_PLAYERS 4

#define NUM_VESSELS 4
#define SERVER_INITIAL_TIMER_VALUE 30

#define GAME_ROUND_LENGTH_SECONDS 300
#define SCOREBOARD_LENGTH_SECONDS 25
#define MUSIC_OFF 0
#define MUSIC_ON 1

#endif
